# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

run_simpers <- function(input_domain_complex_file_name, input_range_complex_file_folder, input_simplicial_map_file, output_range_complex_with_annotation_file_name, output_persistence_file_name, generator_file, is_input_domain_complex_with_annotation, is_output_range_complex_with_annotation, is_elementary, is_generator, fThreshold_, numFiltration, max_dimension_) {
    .Call('_Simpers_run_simpers', PACKAGE = 'Simpers', input_domain_complex_file_name, input_range_complex_file_folder, input_simplicial_map_file, output_range_complex_with_annotation_file_name, output_persistence_file_name, generator_file, is_input_domain_complex_with_annotation, is_output_range_complex_with_annotation, is_elementary, is_generator, fThreshold_, numFiltration, max_dimension_)
}

